// Mocks generated by Mockito 5.4.6 from annotations
// in schedule_note_app/test/cubits/book_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:schedule_note_app/models/book.dart' as _i2;
import 'package:schedule_note_app/repositories/book_repository.dart' as _i3;
import 'package:schedule_note_app/services/book_order_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBook_0 extends _i1.SmartFake implements _i2.Book {
  _FakeBook_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IBookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBookRepository extends _i1.Mock implements _i3.IBookRepository {
  MockIBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Book>> getAll({bool? includeArchived = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#includeArchived: includeArchived}),
            returnValue: _i4.Future<List<_i2.Book>>.value(<_i2.Book>[]),
          )
          as _i4.Future<List<_i2.Book>>);

  @override
  _i4.Future<_i2.Book?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i2.Book?>.value(),
          )
          as _i4.Future<_i2.Book?>);

  @override
  _i4.Future<_i2.Book> create(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#create, [name]),
            returnValue: _i4.Future<_i2.Book>.value(
              _FakeBook_0(this, Invocation.method(#create, [name])),
            ),
          )
          as _i4.Future<_i2.Book>);

  @override
  _i4.Future<_i2.Book> update(_i2.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#update, [book]),
            returnValue: _i4.Future<_i2.Book>.value(
              _FakeBook_0(this, Invocation.method(#update, [book])),
            ),
          )
          as _i4.Future<_i2.Book>);

  @override
  _i4.Future<void> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> archive(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#archive, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reorder(List<_i2.Book>? books) =>
      (super.noSuchMethod(
            Invocation.method(#reorder, [books]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BookOrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookOrderService extends _i1.Mock implements _i5.BookOrderService {
  MockBookOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveBookOrder(List<String>? bookUuids) =>
      (super.noSuchMethod(
            Invocation.method(#saveBookOrder, [bookUuids]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> loadBookOrder() =>
      (super.noSuchMethod(
            Invocation.method(#loadBookOrder, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  List<_i2.Book> applyOrder(List<_i2.Book>? books, List<String>? savedOrder) =>
      (super.noSuchMethod(
            Invocation.method(#applyOrder, [books, savedOrder]),
            returnValue: <_i2.Book>[],
          )
          as List<_i2.Book>);

  @override
  _i4.Future<void> saveCurrentOrder(List<_i2.Book>? books) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrentOrder, [books]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
