-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.book_device_access
(
    book_uuid uuid NOT NULL,
    device_id uuid NOT NULL,
    access_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'owner'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT book_device_access_pkey PRIMARY KEY (book_uuid, device_id)
);

COMMENT ON TABLE public.book_device_access
    IS 'Controls which devices can access which books and their permission level.';

CREATE TABLE IF NOT EXISTS public.books
(
    book_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    device_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    archived_at timestamp with time zone,
    synced_at timestamp with time zone NOT NULL DEFAULT now(),
    version integer NOT NULL DEFAULT 1,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT books_pkey PRIMARY KEY (book_uuid)
);

COMMENT ON TABLE public.books
    IS 'Top-level schedule/record book, keyed by UUID.';

CREATE TABLE IF NOT EXISTS public.charge_items
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    record_uuid uuid NOT NULL,
    event_id uuid,
    item_name text COLLATE pg_catalog."default" NOT NULL,
    item_price integer NOT NULL DEFAULT 0,
    received_amount integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    synced_at timestamp with time zone,
    version integer NOT NULL DEFAULT 1,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT charge_items_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.charge_items
    IS 'Charge items linked to a record (person), optionally associated with an event.';

COMMENT ON COLUMN public.charge_items.record_uuid
    IS 'The person/global record this charge item belongs to.';

COMMENT ON COLUMN public.charge_items.event_id
    IS 'Optional event (visit) associated with this charge item.';

CREATE TABLE IF NOT EXISTS public.devices
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    device_name text COLLATE pg_catalog."default" NOT NULL,
    device_token text COLLATE pg_catalog."default" NOT NULL,
    platform text COLLATE pg_catalog."default",
    registered_at timestamp with time zone NOT NULL DEFAULT now(),
    last_sync_at timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT devices_pkey PRIMARY KEY (id),
    CONSTRAINT devices_device_token_key UNIQUE (device_token)
);

COMMENT ON TABLE public.devices
    IS 'All registered client devices.';

CREATE TABLE IF NOT EXISTS public.events
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    book_uuid uuid NOT NULL,
    record_uuid uuid NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    event_types text COLLATE pg_catalog."default" NOT NULL DEFAULT '["other"]'::text,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    synced_at timestamp with time zone,
    version integer NOT NULL DEFAULT 1,
    is_deleted boolean NOT NULL DEFAULT false,
    is_removed boolean NOT NULL DEFAULT false,
    removal_reason text COLLATE pg_catalog."default",
    is_checked boolean NOT NULL DEFAULT false,
    has_charge_items boolean NOT NULL DEFAULT false,
    original_event_id uuid,
    new_event_id uuid,
    has_note boolean NOT NULL DEFAULT false,
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.events
    IS 'Events (appointments, visits, etc.) for books, each tied to a global record.';

COMMENT ON COLUMN public.events.record_uuid
    IS 'Global record/person/case identifier. Same record_uuid across books shares meta & note.';

COMMENT ON COLUMN public.events.title
    IS 'Event display title, typically defaults to record.name but can be customized.';

COMMENT ON COLUMN public.events.event_types
    IS 'JSON array of event types, e.g. ["consultation","treatment"].';

COMMENT ON COLUMN public.events.has_note
    IS 'Indicates whether this event has an associated note (for quick lookup without JOIN).';

CREATE TABLE IF NOT EXISTS public.notes
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    record_uuid uuid NOT NULL,
    pages_data text COLLATE pg_catalog."default" NOT NULL DEFAULT '[[]]'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    synced_at timestamp with time zone,
    version integer NOT NULL DEFAULT 1,
    is_deleted boolean NOT NULL DEFAULT false,
    locked_by_device_id text COLLATE pg_catalog."default",
    locked_at timestamp with time zone,
    CONSTRAINT notes_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.notes
    IS 'Multi-page note shared by all events for the same global record.';

COMMENT ON COLUMN public.notes.record_uuid
    IS 'One-to-one with records; all events for that record share this note.';

CREATE TABLE IF NOT EXISTS public.records
(
    record_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    record_number text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    name text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    synced_at timestamp with time zone,
    version integer NOT NULL DEFAULT 1,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT records_pkey PRIMARY KEY (record_uuid)
);

COMMENT ON TABLE public.records
    IS 'Global logical record/person/case, shared across all books and events.';

COMMENT ON COLUMN public.records.record_number
    IS 'Global record number. Combined with name, unique when non-empty; empty strings are allowed to duplicate for standalone records.';

CREATE TABLE IF NOT EXISTS public.schedule_drawings
(
    id bigserial NOT NULL,
    book_uuid uuid NOT NULL,
    date timestamp with time zone NOT NULL,
    view_mode integer NOT NULL,
    strokes_data text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    synced_at timestamp with time zone NOT NULL DEFAULT now(),
    version integer NOT NULL DEFAULT 1,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT schedule_drawings_pkey PRIMARY KEY (id),
    CONSTRAINT schedule_drawings_book_date_view_unique UNIQUE (book_uuid, date, view_mode)
);

COMMENT ON TABLE public.schedule_drawings
    IS 'Handwriting overlay on schedule views, per book/date/view_mode.';

CREATE TABLE IF NOT EXISTS public.sync_log
(
    id bigserial NOT NULL,
    device_id uuid NOT NULL,
    operation text COLLATE pg_catalog."default" NOT NULL,
    table_name text COLLATE pg_catalog."default" NOT NULL,
    record_id uuid,
    status text COLLATE pg_catalog."default" NOT NULL,
    error_message text COLLATE pg_catalog."default",
    changes_count integer NOT NULL DEFAULT 0,
    synced_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sync_log_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.sync_log
    IS 'Audit trail of all sync operations.';

ALTER TABLE IF EXISTS public.book_device_access
    ADD CONSTRAINT book_device_access_book_uuid_fkey FOREIGN KEY (book_uuid)
    REFERENCES public.books (book_uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.book_device_access
    ADD CONSTRAINT book_device_access_device_id_fkey FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_book_device_access_device_id
    ON public.book_device_access(device_id);


ALTER TABLE IF EXISTS public.books
    ADD CONSTRAINT books_device_id_fkey FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_books_device_id
    ON public.books(device_id);


ALTER TABLE IF EXISTS public.charge_items
    ADD CONSTRAINT charge_items_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_charge_items_event_id
    ON public.charge_items(event_id);


ALTER TABLE IF EXISTS public.charge_items
    ADD CONSTRAINT charge_items_record_uuid_fkey FOREIGN KEY (record_uuid)
    REFERENCES public.records (record_uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_charge_items_record_uuid
    ON public.charge_items(record_uuid);


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_book_uuid_fkey FOREIGN KEY (book_uuid)
    REFERENCES public.books (book_uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_events_book_uuid
    ON public.events(book_uuid);


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_record_uuid_fkey FOREIGN KEY (record_uuid)
    REFERENCES public.records (record_uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_events_record_uuid
    ON public.events(record_uuid);


ALTER TABLE IF EXISTS public.notes
    ADD CONSTRAINT notes_record_uuid_fkey FOREIGN KEY (record_uuid)
    REFERENCES public.records (record_uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notes_record_uuid
    ON public.notes(record_uuid);


ALTER TABLE IF EXISTS public.schedule_drawings
    ADD CONSTRAINT schedule_drawings_book_uuid_fkey FOREIGN KEY (book_uuid)
    REFERENCES public.books (book_uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_schedule_drawings_book_uuid
    ON public.schedule_drawings(book_uuid);


ALTER TABLE IF EXISTS public.sync_log
    ADD CONSTRAINT sync_log_device_id_fkey FOREIGN KEY (device_id)
    REFERENCES public.devices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sync_log_device_id
    ON public.sync_log(device_id);

END;