import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:http/io_client.dart';

Map<String, String> _loadEnvFile(String path) {
  final file = File(path);
  if (!file.existsSync()) return const {};

  final map = <String, String>{};
  for (final rawLine in file.readAsLinesSync()) {
    final line = rawLine.trim();
    if (line.isEmpty || line.startsWith('#')) continue;
    final idx = line.indexOf('=');
    if (idx <= 0) continue;
    map[line.substring(0, idx).trim()] = line.substring(idx + 1).trim();
  }
  return map;
}

String _resolveValue({
  required String key,
  required Map<String, String> fileEnv,
}) {
  final fromProcess = Platform.environment[key]?.trim();
  if (fromProcess != null && fromProcess.isNotEmpty) return fromProcess;
  final fromFile = fileEnv[key]?.trim();
  if (fromFile != null && fromFile.isNotEmpty) return fromFile;
  return '';
}

http.Client _buildClient(String baseUrl) {
  if (!baseUrl.startsWith('https://')) return http.Client();

  final allowBadCert =
      (Platform.environment['SN_TEST_ALLOW_BAD_CERT'] ?? '1') != '0';
  final ioClient = HttpClient();
  if (allowBadCert) {
    ioClient.badCertificateCallback = (_, __, ___) => true;
  }
  return IOClient(ioClient);
}

String _pickString(Map<String, dynamic> map, {required List<String> keys}) {
  for (final key in keys) {
    final value = map[key];
    if (value != null && value.toString().trim().isNotEmpty) {
      return value.toString();
    }
  }
  throw StateError('Missing expected keys: ${keys.join(', ')}');
}

Future<void> main() async {
  final envFilePath =
      Platform.environment['SN_TEST_ENV_FILE']?.trim().isNotEmpty == true
      ? Platform.environment['SN_TEST_ENV_FILE']!.trim()
      : '.env.integration';
  final fileEnv = _loadEnvFile(envFilePath);

  final baseUrl = _resolveValue(key: 'SN_TEST_BASE_URL', fileEnv: fileEnv);
  final registrationPassword = _resolveValue(
    key: 'SN_TEST_REGISTRATION_PASSWORD',
    fileEnv: fileEnv,
  );
  final bookPassword =
      _resolveValue(key: 'SN_TEST_BOOK_PASSWORD', fileEnv: fileEnv).isEmpty
      ? 'fixture-book-password'
      : _resolveValue(key: 'SN_TEST_BOOK_PASSWORD', fileEnv: fileEnv);

  if (baseUrl.isEmpty) {
    stderr.writeln(
      'Missing required config. Set SN_TEST_BASE_URL (env or $envFilePath).',
    );
    exitCode = 64;
    return;
  }

  final client = _buildClient(baseUrl);
  try {
    final response = await client
        .post(
          Uri.parse('$baseUrl/api/test-fixtures/live-event-metadata'),
          headers: {'Content-Type': 'application/json'},
          body: jsonEncode({
            'password': registrationPassword.isEmpty
                ? 'password'
                : registrationPassword,
            'bookPassword': bookPassword,
          }),
        )
        .timeout(const Duration(seconds: 20));

    if (response.statusCode != 200) {
      throw StateError(
        'Provision fixture failed: ${response.statusCode} ${response.body}',
      );
    }

    final body = jsonDecode(response.body) as Map<String, dynamic>;
    final writeDevice = (body['writeDevice'] as Map).cast<String, dynamic>();
    final readDevice = (body['readDevice'] as Map).cast<String, dynamic>();
    final fixture = (body['fixture'] as Map).cast<String, dynamic>();

    final content =
        '''
# Generated by tool/create_event_metadata_fixture.dart
SN_TEST_BASE_URL=$baseUrl
SN_TEST_REGISTRATION_PASSWORD=${registrationPassword.isEmpty ? 'password' : registrationPassword}
SN_TEST_WRITE_DEVICE_ID=${_pickString(writeDevice, keys: const ['deviceId'])}
SN_TEST_WRITE_DEVICE_TOKEN=${_pickString(writeDevice, keys: const ['deviceToken'])}
SN_TEST_DEVICE_ID=${_pickString(writeDevice, keys: const ['deviceId'])}
SN_TEST_DEVICE_TOKEN=${_pickString(writeDevice, keys: const ['deviceToken'])}
SN_TEST_READ_DEVICE_ID=${_pickString(readDevice, keys: const ['deviceId'])}
SN_TEST_READ_DEVICE_TOKEN=${_pickString(readDevice, keys: const ['deviceToken'])}
SN_TEST_BOOK_UUID=${_pickString(fixture, keys: const ['bookUuid'])}
SN_TEST_EVENT_ID=${_pickString(fixture, keys: const ['eventId'])}
SN_TEST_RECORD_UUID=${_pickString(fixture, keys: const ['recordUuid'])}
SN_TEST_BOOK_PASSWORD=$bookPassword
SN_TEST_FIXTURE_AUTO_CLEANUP=1
''';
    await File(envFilePath).writeAsString(content);

    stdout.writeln('Created integration fixtures successfully.');
    stdout.writeln('Wrote config to $envFilePath');
    stdout.writeln('Write Device ID: ${writeDevice['deviceId']}');
    stdout.writeln('Read Device ID: ${readDevice['deviceId']}');
    stdout.writeln('Fixture Book UUID: ${fixture['bookUuid']}');
  } catch (e) {
    stderr.writeln('Failed to create integration fixture: $e');
    exitCode = 1;
  } finally {
    client.close();
  }
}
